name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' # Specify your desired Go version

      - name: Download Go modules
        run: go mod tidy

      - name: Run Go tests
        run: go test -json -cover -coverprofile coverage.out -v ./... # -v for verbose output, ./... to run all tests in subdirectories
      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage.out
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: hackafterdark/carta